#!/bin/bash
atm_pe=4
ocn_pe=3
chm_pe=1
ln -fs ../bin/atm_driver
ln -fs ../bin/ocn_driver
ln -fs ../bin/chm_driver
mpiexec -n ${atm_pe} ./atm_driver : \
        -n ${ocn_pe} ./ocn_driver : \
        -n ${chm_pe} ./chm_driver 1> Stdout 2>Stderr
